version: "3"
services:
  invoices:
    container_name: ms-agreement
    image: 'ms-agreement'
    network_mode: bridge
    restart: always
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile
#      TODO Verify correct port used in production
    ports:
      - "8725:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'prod'
